### ISSUE TITLE
issues with delta code samples

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-devx-api#279]
Hey Team,
I've found two issues with delta samples
- Missing to reference a variable that was already in the sample
- Missing the delta token all together

They are "fixed" (to illustrate what's wrong) in this PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/9042 
[AB#7028](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7028)

**Comment by baywet** [comment]
after syncing offline I reverted the code snippets changes so my PR can make it through with other changes. Here are the commits I was mentionning.
https://github.com/microsoftgraph/microsoft-graph-docs/pull/9042/commits/8c0b2b17f6c3013330cfc26010f4203fc24680f5
https://github.com/microsoftgraph/microsoft-graph-docs/pull/9042/commits/6d320c6664d23cd85ebbf85e59e3a9496432cdfa

**Comment by ddyett** [comment]
@zengin can you track this one.

**Comment by zengin** [comment]
@baywet, I believe these are fixed with SDK v5 and corresponding snippet fixes. Can you please confirm?

**Comment by baywet** [comment]
ah, another of my "legacy" issues, this one from when I was a PM for the feature :)

This is still wrong for two reasons

```CSharp
var graphClient = new GraphServiceClient(requestAdapter);

var result = await graphClient.Me.CalendarView.Delta.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Deltatoken = "R0usmcMDNGg0J1E";
	requestConfiguration.Headers.Add("Prefer", "odata.maxpagesize=2");
});
```

1. we don't project a Deltatoken, or Skiptoken queryparameter in the conversion process
2. We should technically be showing them how to use the complete deta/skip link with a request builder, we should encourage customers to parse those links, they are supposed to be opaque.
